### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by lkaczanowski** [jacentino/SqlFun#1]
Hi,

Are you planning to publish your library on nuget.org?

**Comment by jacentino** [comment]
Hi,

Definitely, I'm going to publish it.
I have to solve two things before.
The first one is initialization/configuration code.
For now, you have to pass 4 params to sql function:

```fsharp
let sql commandText = 
    sql createConnection None defaultParamBuilder defaultRowBuilder commandText
```

I'm going to define some config record type, to make whole thing less sensitive to
extensions.
It could look like this:

```fsharp

let config = { QueryGeneratorConfig.Defult with connectionBuilder = createConnection }
 
let sql commandText = 
    sql config commandText
```


The second thing is versioning of FSharp.Core. Some nuget packages make it wrong and I don't like to publish another one.

After dealing with it, I'll publish SqlFun.

**Comment by jacentino** [comment]
SqlFun prerelease version is published n nuget.
