### ISSUE TITLE
Cancellation Token

### ISSUE THREAD

**Issue by ShalokShalom** [jacentino/SqlFun#10]
Do you have cancellation token support evaluated?

https://devblogs.microsoft.com/azure-sdk/how-to-use-cancellationtokens-to-cancel-tasks-in-the-azure-sdk-for-net/

Thanks 🙏

**Comment by jacentino** [comment]
Hi,

No, I didn't test it. I'll do some experiments in a few days.

Cheers,
Jacek

wt., 18 paź 2022 o 22:04 ShalokShalom ***@***.***> napisał(a):

**Comment by jacentino** [comment]
Hi, 

I tried it. Cancellation tokens just work. Passing token to Async.Start or any other method firing async workflow is enough.

Jacek

**Comment by ShalokShalom** [comment]
It's not passing a cancellationtoken to any `ExecuteReaderAsync` or variants that talk to the database

Make the query take 30 seconds to return and tell me that you dont have database connections still open after you cancel it :)

**Comment by jacentino** [comment]
You're right. I wrote wrong test. The async workflow in the test was cancelled before start of a long running procedure. I modified it and now I have proper diagnostics. I'll prepare new version of SqlFun in a few days.

**Comment by jacentino** [comment]
V 2.2.0 handles cancellation tokens correctly.

**Comment by ShalokShalom** [comment]
Wonderful 🥳
