### ISSUE TITLE
A question about property mapping

### ISSUE THREAD

**Issue by sheridanchris** [jacentino/SqlFun#19]
Often times I use postgresql where its idiomatic to use `snake_case` for column names (`PascalCase` requires escaping column, tables, and types with quotations) . Is there any way to configure a mapper for `snake_case` -> `PascalCase` when reading query results into record types?

**Comment by jacentino** [comment]
Unfortunately, it's not. If you don't like snake case in both - db and
code, you can use sql aliases.

pon., 21 sie 2023 o 02:47 Christian Sheridan ***@***.***>
napisał(a):
