### ISSUE TITLE
sqlite: don't matching query columns as expected

### ISSUE THREAD

**Issue by yuri-potatoq** [jacentino/SqlFun#24]
I was testing some ways to build queries from some table adding some additional field on query time.
Given the follow simple schema:
```sql
CREATE TABLE Main (
    pk INTEGER PRIMARY KEY AUTOINCREMENT 
    ,data TEXT  
);

INSERT INTO Main(data) VALUES ('Initial Data'), ('Last Data');
```

I'd expected to be able query like that:
```fsharp
type Main = {Tag: string; Data : string}

type Repo(db: Db) =
    member val query: int -> AsyncDb<Main list> =
        db.sql """
            SELECT
                'Some Tag' as tag
                ,m.data
            FROM Main as m
            WHERE m.pk = @id
        """
```

But for some reason, i get stuck with the error below.
```csharp
SqlFun.Exceptions.CompileTimeException: Error generating function Int32 -> IDataContext -> Main list Async for sql command 
            SELECT
                'Some Tag' as tag
                ,m.data
            FROM Main as m
            WHERE m.pk = @id
        
 ---> System.Exception: No column found for Tag field. Expected: Tag
 ---> System.InvalidOperationException: No coercion operator is defined between types 'System.Byte[]' and 'System.String'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at SqlFun.ResultBuilder.buildColumnAccessor[a](ParameterExpression reader, Type colType, a ordinal, Type targetType) in C:\Projekty\FSharp\SqlFun\SqlFun\ResultBuilder.fs:line 267
   at SqlFun.ResultBuilder.getRowBuilderExpression[a](FSharpFunc`2 nextRB, a reader, FSharpMap`2 metadata, String prefix, String fieldName, Type returnType) in C:\Projekty\FSharp\SqlFun\SqlFun\ResultBuilder.fs:line 344
```

But i realize that when the WHERE clause is changed to `WHERE m.pk <> @id` that work as expected for some reason. :confused: 
Maybe the coercion made in compile time is getting some unexpected parser error?

**Comment by yuri-potatoq** [comment]
p.s.: When i follow the error message to fix it by change the result type. I got a wrong result:
```fsharp
[{ Tag = []
   Data = "Initial Data" }]
```

**Comment by jacentino** [comment]
Hi Yuri,

The problem is, that Microsoft.Data.SQLite incorrectly handles string literals when a command is executed in SchemaOnly mode. String literals in select clause are recognised as byte arrays instead of strings (i.e. IDataReader.GetFieldType() returns typeof<Byte[]>).
SqlFun uses SchemaOnly readers to discover result structure before generating code, so it's quite crucial.

This issue doesn't appear when using **System.Data.SQLite** and I recommend it to use with SqlFun.

**Comment by jacentino** [comment]
Of course, If you are sure you want to use Microsoft.Data.SQLite I can report the issue to SQLite team in Microsoft.

**Comment by yuri-potatoq** [comment]
I really appreciate your help.
I don't think i need to use specific driver library, so that fit well for me. Thanks!
