### ISSUE TITLE
Upgrade to net5 and use of the new SqlDataClient?

### ISSUE THREAD

**Issue by halcwb** [jacentino/SqlFun#5]
Is it possible to upgrade this project to net5 and use of the [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient)? Then you could us this on any OS.

**Comment by jacentino** [comment]
Hi Casper,

For now, you can write multiplatform applications using SqlFun on .NET Core, since it is .NEt Standard library.
Of course, I'll upgrade it to .NET 5 too, but I need some time, I guess, that I'll be ready with it in one month.

**Comment by jacentino** [comment]
SqlFun working with Microsoft.Data.SqlClient is now available as a nuget package SqlFun.MsDataSql.
